[build]
  command = "pnpm build"
  functions = "netlify/functions"
  publish = "build"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  [[redirects]]
    from = "/admin/*"
    to = "/"
    status = 200
    force = true


  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  [dev]
    command = "pnpm develop" # Command to start your dev server
    targetPort = 1337
    port = 8080 # Port that the dev server will be listening on
    publish = "build" # Folder with the static content for _redirect file
